apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.modsec_server.name }}
  name: {{ .Values.modsec_server.name }}-modsec
  namespace: {{ .Values.namespace }}
spec:
  path: /
  port:
    targetPort: 8001
  to:
    kind: Service
    name: {{ .Values.modsec_server.name }}-service
    weight: 100
  wildcardPolicy: None
