apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.modsec_server.name }}
  name: {{ .Values.modsec_server.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: {{ .Values.modsec_server.name }}
  sessionAffinity: None
