apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.webgoat_server.name }}
  name: {{ .Values.webgoat_server.name }}-goat
  namespace: {{ .Values.namespace }}
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  path: /WebGoat
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.webgoat_server.name }}-service
    weight: 100
  wildcardPolicy: None
---
  apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.webgoat_server.name }}
  name: {{ .Values.webgoat_server.name }}-wolf
  namespace: {{ .Values.namespace }}
spec:
  path: /
  port:
    targetPort: 9090
  to:
    kind: Service
    name: {{ .Values.webgoat_server.name }}-wolfservice
    weight: 100
  wildcardPolicy: None
