apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.webgoat_server.name }}
    app.kubernetes.io/part-of: {{ .Values.webgoat_server.name }}
  name: {{ .Values.webgoat_server.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.webgoat_server.name }}
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.webgoat_server.name }}
    app.kubernetes.io/part-of: {{ .Values.webgoat_server.name }}
  name: {{ .Values.webgoat_server.name }}-wolfservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 9090-tcp
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: {{ .Values.webgoat_server.name }}
  sessionAffinity: None
